spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.3:3306/gctos
    username: gctos
    password: gctos
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


